# Generated by Django 3.2.6 on 2021-09-15 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Images/')),
                ('power', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('uses', models.CharField(max_length=500)),
                ('side_effect', models.CharField(max_length=500)),
                ('sub_brands', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medicine_group')),
            ],
        ),
    ]
