# Generated by Django 3.2.6 on 2021-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_medicine_side_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='uses',
            field=models.TextField(max_length=500),
        ),
    ]
