# Generated by Django 3.2.6 on 2021-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_medicine_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='doses',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default='Images/default.jpg', upload_to='Images/'),
        ),
    ]
