# Generated by Django 3.2.6 on 2021-09-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210916_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='sub_brands',
            new_name='alternate_brands',
        ),
    ]
