# Generated by Django 3.2.6 on 2021-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_sub_brands_medicine_alternate_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='doses',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='uses',
            field=models.TextField(max_length=2000),
        ),
    ]
