# Generated by Django 3.2.7 on 2021-09-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210918_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ques',
            new_name='question',
        ),
    ]
