# Generated by Django 3.2.7 on 2021-09-18 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_ques_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 8, 35, 58, 744149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 8, 35, 58, 744149, tzinfo=utc)),
        ),
    ]
